### ISSUE TITLE
Flexbox examples

### ISSUE THREAD

**Issue by jmjpro** [zopyx/print-css-rocks#1]
I would love to see some flexbox examples. I haven't had a luck getting tools such as prince or weasyprint to play nicely with flexbox. See for example this layout: https://codepen.io/jmjpro/full/JyVYQV/

**Comment by zopyx** [comment]
Flexbox is not part of the CSS Paged Media standard. Only PDFreactor supports Flexboxes. There is one example here http://www.pdfreactor.com/samples/

As far as I know: CSS grid will replace flexboxes.

Nothing I want to do here because it is neither standard nor supported by the majority of the tools.
